Review `elabctl` script (our defaults, macOS support).

diff --git a/elabctl b/elabctl
--- a/elabctl
+++ b/elabctl
@@ -1,22 +1,27 @@
 #!/usr/bin/env bash
 # https://www.elabftw.net
 
+CODE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
 ###############################################################
 # CONFIGURATION
+# Via a config file…
+declare -r USER_CONF_FILE="${CODE_DIR}/elabctl.conf"
+
+# … of these defaults
 # where do you want your backups to end up?
-declare BACKUP_DIR='/var/backups/elabftw'
-# where do we store the config file?
-declare CONF_FILE='/etc/elabftw.yml'
+declare BACKUP_DIR="${CODE_DIR}/var/backups"
+# where do we store the Docker config file?
+declare DOCKER_CONF_FILE="${CODE_DIR}/docker-compose.yml"
 # where do we store the MySQL database and the uploaded files?
-declare DATA_DIR='/var/elabftw'
+declare DATA_DIR="${CODE_DIR}/var/uploads"
 # where do we store the logs?
-declare LOG_FILE='/var/log/elabftw.log'
+declare LOG_FILE="${CODE_DIR}/var/log/elabftw.log"
 # END CONFIGURATION
 ###############################################################
 
-declare -r MAN_FILE='/usr/share/man/man1/elabctl.1.gz'
-declare -r ELABCTL_VERSION='0.6.2'
-declare -r USER_CONF_FILE='/etc/elabctl.conf'
+declare -r MAN_FILE="/usr/share/man/man1/elabctl.1.gz"
+declare -r ELABCTL_VERSION="0.6.2"
 
 # Now we load the configuration file for custom directories set by user
 if [ -f ${USER_CONF_FILE} ]; then
@@ -40,7 +45,7 @@ function ascii()
 # create a mysqldump and a zip archive of the uploaded files
 function backup()
 {
-    echo "Using backup directory $BACKUP_DIR"
+    echo "Using backup directory ${BACKUP_DIR}"
 
     if ! ls -A "${BACKUP_DIR}" > /dev/null 2>&1; then
         mkdir -p "${BACKUP_DIR}"
@@ -54,7 +59,7 @@ function backup()
     local -r dumpfile="${BACKUP_DIR}/mysql_dump-${date}.sql"
 
     # dump sql
-    docker exec mysql bash -c 'mysqldump -u$MYSQL_USER -p$MYSQL_PASSWORD -r dump.sql $MYSQL_DATABASE' > /dev/null 2>&1
+    docker exec mysql bash -c "mysqldump -u${MYSQL_USER} -p${MYSQL_PASSWORD} -r dump.sql ${MYSQL_DATABASE}" > /dev/null 2>&1
     # copy it from the container to the host
     docker cp mysql:dump.sql "$dumpfile"
     # compress it to the max
@@ -62,9 +67,29 @@ function backup()
     # make a zip of the uploads folder
     zip -rq "$zipfile" ${DATA_DIR}/web -x ${DATA_DIR}/web/tmp\*
     # add the config file
-    zip -rq "$zipfile" $CONF_FILE
+    zip -rq "$zipfile" $DOCKER_CONF_FILE
 
     echo "Done. Copy ${BACKUP_DIR} over to another computer."
+}
+
+function detectOS()
+{
+    if test -e /etc/os-release; then
+        source /etc/os-release
+        OS=$ID
+
+    elif [ `uname` == "Darwin" ]; then
+        OS='macos'
+
+    # for CentOS 6.8, see #368
+    elif grep -qi centos /etc/*-release; then
+        echo "It looks like you are using CentOS 6.8 which is using a very old kernel not compatible/stable with Docker. It is not recommended to use eLabFTW in Docker with this setup. Please have a look at the installation instructions without Docker."
+        exit 1
+
+    else
+        echo "Could not detect your OS. Please open a github issue!"
+        exit 1
+    fi
 }
 
 function getUserconf()
@@ -77,9 +102,17 @@ function getUserconf()
 
 function getDeps()
 {
-    if [ "$ID" == "ubuntu" ] || [ "$ID" == "debian" ] || [ "$ID" == "linuxmint" ]; then
+    if [ "$OS" != "macos" ]; then
+        is-root
+    fi
+
+    if [ "$OS" == "ubuntu" ] || [ "$OS" == "debian" ] || [ "$OS" == "linuxmint" ]; then
         echo "Synchronizing packages index. Please wait…"
         apt-get update >> $LOG_FILE 2>&1
+    elif [ "$OS" == "macos" ] && ! hash brew 2>/dev/null; then
+        # See https://brew.sh/
+        echo "Installing prerequisite package: brew. Please wait…"
+        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
     fi
 
     if ! hash dialog 2>/dev/null; then
@@ -101,58 +134,41 @@ function getDeps()
         echo "Installing prerequisite package: git. Please wait…"
         install-pkg git
     fi
-
 }
 
 function getDistrib()
 {
-    # let's first try to read /etc/os-release
-    if test -e /etc/os-release
-    then
+    # pacman = package manager
 
-        # source the file
-        . /etc/os-release
+    # DEBIAN / UBUNTU / MINT
+    if [ "$OS" == "ubuntu" ] || [ "$OS" == "debian" ] || [ "$OS" == "linuxmint" ]; then
+        PACMAN="apt-get -y install"
 
-        # pacman = package manager
+    # FEDORA
+    elif [ "$OS" == "fedora" ]; then
+        PACMAN="dnf -y install"
 
-        # DEBIAN / UBUNTU / MINT
-        if [ "$ID" == "ubuntu" ] || [ "$ID" == "debian" ] || [ "$ID" == "linuxmint" ]; then
-            PACMAN="apt-get -y install"
+    # CENTOS
+    elif [ "$OS" == "centos" ]; then
+        PACMAN="yum -y install"
+        # we need this to install python-pip
+        install-pkg epel-release
 
-        # FEDORA
-        elif [ "$ID" == "fedora" ]; then
-            PACMAN="dnf -y install"
+    # RED HAT
+    elif [ "$OS" == "rhel" ]; then
+        PACMAN="yum -y install"
 
-        # CENTOS
-        elif [ "$ID" == "centos" ]; then
-            PACMAN="yum -y install"
-            # we need this to install python-pip
-            install-pkg epel-release
+    # ARCH IS THE BEST
+    elif [ "$OS" == "arch" ]; then
+        PACMAN="pacman -Sy --noconfirm"
 
-        # RED HAT
-        elif [ "$ID" == "rhel" ]; then
-            PACMAN="yum -y install"
+    # OPENSUSE
+    elif [ "$OS" == "opensuse" ]; then
+        PACMAN="zypper -n install"
 
-        # ARCH IS THE BEST
-        elif [ "$ID" == "arch" ]; then
-            PACMAN="pacman -Sy --noconfirm"
-
-        # OPENSUSE
-        elif [ "$ID" == "opensuse" ]; then
-            PACMAN="zypper -n install"
-        else
-            echo "What distribution are you running? Please open a github issue!"
-            exit 1
-        fi
-    # for CentOS 6.8, see #368
-    elif grep -qi centos /etc/*-release
-    then
-        echo "It looks like you are using CentOS 6.8 which is using a very old kernel not compatible/stable with Docker. It is not recommended to use eLabFTW in Docker with this setup. Please have a look at the installation instructions without Docker."
-        exit 1
-
-    else
-        echo "Could not load /etc/os-release to guess distribution. Please open a github issue!"
-        exit 1
+    # MACOS
+    elif [ "$OS" == "macos" ]; then
+        PACMAN="brew install"
     fi
 }
 
@@ -181,7 +197,6 @@ function help()
         php-logs        Show last 15 lines of nginx error log
         refresh         Recreate the containers if they need to be
         restart         Restart the containers
-        self-update     Update the elabctl script
         status          Show status of running containers
         start           Start the containers
         stop            Stop the containers
@@ -245,7 +260,7 @@ function install()
         This script will automatically install eLabFTW in a Docker container." 0 0
 
         dialog --colors --backtitle "$backtitle" --title "$title" --yes-label "Looks good to me" --no-label "Download example conf and quit" --yesno "\nHere is what will happen:\n
-        The main configuration file will be created at: \Z4${CONF_FILE}\Zn\n
+        The main configuration file will be created at: \Z4${DOCKER_CONF_FILE}\Zn\n
         The configuration file for elabctl will be created at: \Z4${USER_CONF_FILE}\Zn\n
         A directory holding elabftw data (mysql + uploaded files) will be created at: \Z4${DATA_DIR}\Zn\n
         A log file of the installation process will be created at: \Z4${LOG_FILE}\Zn\n
@@ -327,7 +342,7 @@ function install()
         Enter your email address:\n" 0 0 --output-fd 1)
                         else
                             # show warning about need of edit config file for own certs
-                            dialog --colors --backtitle "$backtitle" --title "$title" --msgbox "\nMake sure to \Zb\Z4edit the configuration file ${CONF_FILE}\Zn to point to your certificates before starting the containers!\n" 0 0
+                            dialog --colors --backtitle "$backtitle" --title "$title" --msgbox "\nMake sure to \Zb\Z4edit the configuration file ${DOCKER_CONF_FILE}\Zn to point to your certificates before starting the containers!\n" 0 0
                         fi
                     fi
                 fi
@@ -356,39 +371,39 @@ function install()
 
     echo 50 | dialog --backtitle "$backtitle" --title "$title" --gauge "Grabbing the docker-compose configuration file" 20 80
     # make a copy of an existing conf file
-    if [ -e $CONF_FILE ]; then
+    if [ -e $DOCKER_CONF_FILE ]; then
         echo 55 | dialog --backtitle "$backtitle" --title "$title" --gauge "Making a copy of the existing configuration file." 20 80
-        \cp $CONF_FILE ${CONF_FILE}.old
+        \cp $DOCKER_CONF_FILE ${DOCKER_CONF_FILE}.old
     fi
 
-    wget -q https://raw.githubusercontent.com/elabftw/elabimg/master/src/docker-compose.yml-EXAMPLE -O "$CONF_FILE"
+    wget -q https://raw.githubusercontent.com/elabftw/elabimg/master/src/docker-compose.yml-EXAMPLE -O "$DOCKER_CONF_FILE"
     # setup restrictive permissions
-    chmod 600 "$CONF_FILE"
+    chmod 600 "$DOCKER_CONF_FILE"
     sleep 1
 
     # elab config
     echo 50 | dialog --backtitle "$backtitle" --title "$title" --gauge "Adjusting configuration" 20 80
     secret_key=$(curl --silent https://demo.elabftw.net/install/generateSecretKey.php)
-    sed -i -e "s/SECRET_KEY=/SECRET_KEY=$secret_key/" $CONF_FILE
-    sed -i -e "s/SERVER_NAME=localhost/SERVER_NAME=$servername/" $CONF_FILE
-    sed -i -e "s:/var/elabftw:${DATA_DIR}:" $CONF_FILE
+    sed -i -e "s/SECRET_KEY=/SECRET_KEY=$secret_key/" $DOCKER_CONF_FILE
+    sed -i -e "s/SERVER_NAME=localhost/SERVER_NAME=$servername/" $DOCKER_CONF_FILE
+    sed -i -e "s:/var/elabftw:${DATA_DIR}:" $DOCKER_CONF_FILE
 
     # disable https
     if [ $usehttps = 0 ]; then
-        sed -i -e "s/DISABLE_HTTPS=false/DISABLE_HTTPS=true/" $CONF_FILE
+        sed -i -e "s/DISABLE_HTTPS=false/DISABLE_HTTPS=true/" $DOCKER_CONF_FILE
     fi
 
     # enable letsencrypt
     if [ $hasdomain -eq 1 ]; then
         # even if we don't use Let's Encrypt, for using TLS certs we need this to be true, and volume mounted
-        sed -i -e "s:ENABLE_LETSENCRYPT=false:ENABLE_LETSENCRYPT=true:" $CONF_FILE
-        sed -i -e "s:#- /etc/letsencrypt:- /etc/letsencrypt:" $CONF_FILE
+        sed -i -e "s:ENABLE_LETSENCRYPT=false:ENABLE_LETSENCRYPT=true:" $DOCKER_CONF_FILE
+        sed -i -e "s:#- /etc/letsencrypt:- /etc/letsencrypt:" $DOCKER_CONF_FILE
     fi
 
     # mysql config
-    sed -i -e "s/MYSQL_ROOT_PASSWORD=secr3t/MYSQL_ROOT_PASSWORD=$rootpass/" $CONF_FILE
-    sed -i -e "s/MYSQL_PASSWORD=secr3t/MYSQL_PASSWORD=$pass/" $CONF_FILE
-    sed -i -e "s/DB_PASSWORD=secr3t/DB_PASSWORD=$pass/" $CONF_FILE
+    sed -i -e "s/MYSQL_ROOT_PASSWORD=secr3t/MYSQL_ROOT_PASSWORD=$rootpass/" $DOCKER_CONF_FILE
+    sed -i -e "s/MYSQL_PASSWORD=secr3t/MYSQL_PASSWORD=$pass/" $DOCKER_CONF_FILE
+    sed -i -e "s/DB_PASSWORD=secr3t/DB_PASSWORD=$pass/" $DOCKER_CONF_FILE
 
     sleep 1
 
@@ -411,7 +426,7 @@ function install()
         In the mean time, check out what to do after an install:\n
         \Z1====>\Zn https://doc.elabftw.net/postinstall.html\n\n
         The log file of the install is here: $LOG_FILE\n
-        The configuration file for docker-compose is here: \Z4$CONF_FILE\Zn\n
+        The configuration file for docker-compose is here: \Z4$DOCKER_CONF_FILE\Zn\n
         Your data folder is: \Z4${DATA_DIR}\Zn. It contains the MySQL database and uploaded files.\n
         You can use 'docker logs -f elabftw' to follow the starting up of the container.\n
         See 'man elabctl' to backup or update." 20 80
@@ -424,9 +439,18 @@ function install-pkg()
     $PACMAN "$1" >> $LOG_FILE 2>&1
 }
 
+function is-root()
+{
+    if [ $EUID != 0 ]; then
+        echo "You don't have sufficient permissions. Try with:"
+        echo "sudo elabctl $1"
+        exit 1
+    fi
+}
+
 function is-installed()
 {
-    if [ ! -f $CONF_FILE ]; then
+    if [ ! -f $DOCKER_CONF_FILE ]; then
         echo "###### ERROR ##########################################################"
         echo "Configuration file could not be found! Did you run the install command?"
         echo "#######################################################################"
@@ -457,18 +481,10 @@ function restart()
     start
 }
 
-function self-update()
-{
-    getMan
-    wget -qO- https://raw.githubusercontent.com/elabftw/elabctl/master/elabctl.sh > /tmp/elabctl
-    chmod +x /tmp/elabctl
-    mv /tmp/elabctl /usr/bin/elabctl
-}
-
 function start()
 {
     is-installed
-    docker-compose -f "$CONF_FILE" up -d
+    docker-compose -f "$DOCKER_CONF_FILE" up -d
 }
 
 function status()
@@ -478,7 +494,7 @@ function status()
 
 function stop()
 {
-    docker-compose -f "$CONF_FILE" down
+    docker-compose -f "$DOCKER_CONF_FILE" down
 }
 
 function uninstall()
@@ -497,9 +513,9 @@ function uninstall()
 
     dialog --backtitle "$backtitle" --title "$title" --yesno "\nDo you want to delete the backups, too?" 0 0
     if [ $? -eq 0 ]; then
-        rmbackup='y'
+        rmbackup="y"
     else
-        rmbackup='n'
+        rmbackup="n"
     fi
 
     dialog --backtitle "$backtitle" --title "$title" --ok-label "Skip timer" --cancel-label "Cancel uninstall" --pause "\nRemoving everything in 10 seconds. Stop now you fool!\n" 20 40 10
@@ -516,13 +532,13 @@ function uninstall()
     fi
 
     # remove config file and eventual backup
-    if [ -f "${CONF_FILE}.old" ]; then
-        rm -f "${CONF_FILE}.old"
-        echo "[x] Deleted ${CONF_FILE}.old"
+    if [ -f "${DOCKER_CONF_FILE}.old" ]; then
+        rm -f "${DOCKER_CONF_FILE}.old"
+        echo "[x] Deleted ${DOCKER_CONF_FILE}.old"
     fi
-    if [ -f "$CONF_FILE" ]; then
-        rm -f "$CONF_FILE"
-        echo "[x] Deleted $CONF_FILE"
+    if [ -f "$DOCKER_CONF_FILE" ]; then
+        rm -f "$DOCKER_CONF_FILE"
+        echo "[x] Deleted $DOCKER_CONF_FILE"
     fi
     # remove logfile
     if [ -f "$LOG_FILE" ]; then
@@ -535,7 +551,7 @@ function uninstall()
         echo "[x] Deleted $DATA_DIR"
     fi
     # remove backup dir
-    if [ $rmbackup == 'y' ] && [ -d "$BACKUP_DIR" ]; then
+    if [ $rmbackup == "y" ] && [ -d "$BACKUP_DIR" ]; then
         rm -rf "$BACKUP_DIR"
         echo "[x] Deleted $BACKUP_DIR"
     fi
@@ -553,7 +569,7 @@ function update()
     echo "Before updating, a backup will be created."
     backup
     echo "Backup done, now updating."
-    docker-compose -f "$CONF_FILE" pull
+    docker-compose -f "$DOCKER_CONF_FILE" pull
     restart
 }
 
@@ -575,12 +591,7 @@ function version()
 
 # SCRIPT BEGIN
 
-# root only
-if [ $EUID != 0 ]; then
-    echo "You don't have sufficient permissions. Try with:"
-    echo "sudo elabctl $1"
-    exit 1
-fi
+detectOS
 
 # only one argument allowed
 if [ $# != 1 ]; then
@@ -602,7 +613,7 @@ esac
 
 # available commands
 declare -A commands
-for valid in backup help info infos install logs php-logs self-update start status stop refresh restart uninstall update upgrade usage version
+for valid in backup help info infos install logs php-logs start status stop refresh restart uninstall update upgrade usage version
 do
     commands[$valid]=1
 done
@@ -611,7 +622,7 @@ if [[ ${commands[$1]} ]]; then
     # exit if variable isn't set
     set -u
     version
-    echo "Using configuration file: "$CONF_FILE""
+    echo "Using configuration file: "$DOCKER_CONF_FILE""
     echo ""
     $1
 else
